### ISSUE TITLE
ISSUE about 'make'

### ISSUE THREAD

**Issue by JasonLu0920** [shichaog/RNNAec#1]
Hi Shichao
 It seems to be something wrong when I make it, whether my configs is fault? Thank you Shichao!

jason@bogon:~/rnnaec/RNNAec$ make
make  all-am
make[1]: Entering directory '/home/jason/rnnaec/RNNAec'
  CC       src/deecho.lo
src/deecho.c: In function ‘compute_frame_features’:
src/deecho.c:319:9: warning: unused variable ‘pitch_buf’ [-Wunused-variable]
   float pitch_buf[PITCH_BUF_SIZE];
         ^~~~~~~~~
src/deecho.c: In function ‘gain_pitch_filter’:
src/deecho.c:460:9: warning: unused variable ‘rf’ [-Wunused-variable]
   float rf[FREQ_SIZE] = {0};
         ^~
src/deecho.c:459:9: warning: unused variable ‘r’ [-Wunused-variable]
   float r[NB_BANDS];
         ^
src/deecho.c:457:37: warning: unused parameter ‘Ex_near’ [-Wunused-parameter]
 void gain_pitch_filter(const float *Ex_near, const float *Ex_far, const float *Exp_near, const float *Exp_far, float *g) {
                                     ^~~~~~~
src/deecho.c:457:59: warning: unused parameter ‘Ex_far’ [-Wunused-parameter]
 void gain_pitch_filter(const float *Ex_near, const float *Ex_far, const float *Exp_near, const float *Exp_far, float *g) {
                                                           ^~~~~~
  CC       src/rnn.lo
  CC       src/rnn_data.lo
  CC       src/rnn_reader.lo
  CC       src/pitch.lo
  CC       src/kiss_fft.lo
  CC       src/celt_lpc.lo
  CCLD     librnnaec.la
ar: `u' modifier ignored since `D' is the default (see `U')
  CC       examples/rnnaec_demo.o
examples/rnnaec_demo.c: In function ‘main’:
examples/rnnaec_demo.c:53:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(tmp, sizeof(short), FRAME_SIZE, f1);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
examples/rnnaec_demo.c:56:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
     fread(tmp, sizeof(short), FRAME_SIZE, f2);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  CCLD     examples/rnnaec_demo
make[1]: *** No rule to make target 'AUTHORS', needed by 'all-am'.  Stop.
make[1]: Leaving directory '/home/jason/rnnaec/RNNAec'
Makefile:411: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by shichaog** [comment]
> 
> 
> Hi Shichao
> It seems to be something wrong when I make it, whether my configs is fault? Thank you Shichao!
> 
> jason@bogon:~/rnnaec/RNNAec$ make make all-am make[1]: Entering directory '/home/jason/rnnaec/RNNAec' CC src/deecho.lo src/deecho.c: In function ‘compute_frame_features’: src/deecho.c:319:9: warning: unused variable ‘pitch_buf’ [-Wunused-variable] float pitch_buf[PITCH_BUF_SIZE]; ^~~~~~~~~ src/deecho.c: In function ‘gain_pitch_filter’: src/deecho.c:460:9: warning: unused variable ‘rf’ [-Wunused-variable] float rf[FREQ_SIZE] = {0}; ^~
> src/deecho.c:459:9: warning: unused variable ‘r’ [-Wunused-variable]
> float r[NB_BANDS];
> ^
> src/deecho.c:457:37: warning: unused parameter ‘Ex_near’ [-Wunused-parameter]
> void gain_pitch_filter(const float *Ex_near, const float *Ex_far, const float *Exp_near, const float *Exp_far, float *g) {
> ^~~~~~~
> src/deecho.c:457:59: warning: unused parameter ‘Ex_far’ [-Wunused-parameter]
> void gain_pitch_filter(const float *Ex_near, const float *Ex_far, const float *Exp_near, const float *Exp_far, float *g) {
> ^~~~~~
> CC src/rnn.lo
> CC src/rnn_data.lo
> CC src/rnn_reader.lo
> CC src/pitch.lo
> CC src/kiss_fft.lo
> CC src/celt_lpc.lo
> CCLD librnnaec.la
> ar: `u' modifier ignored since `D' is the default (see `U')
> CC examples/rnnaec_demo.o
> examples/rnnaec_demo.c: In function ‘main’:
> examples/rnnaec_demo.c:53:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
> fread(tmp, sizeof(short), FRAME_SIZE, f1);
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> examples/rnnaec_demo.c:56:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
> fread(tmp, sizeof(short), FRAME_SIZE, f2);
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> CCLD examples/rnnaec_demo
> make[1]: *** No rule to make target 'AUTHORS', needed by 'all-am'. Stop.
> make[1]: Leaving directory '/home/jason/rnnaec/RNNAec'
> Makefile:411: recipe for target 'all' failed
> make: *** [all] Error 2

Sorry I fogot AUTHORS file, I'll push it later, Please try it tomorrow.

**Comment by JasonLu0920** [comment]
Thank you for your reply! I 've got it! Because I have your previous edition, I copied AUTHOR from it, and now, it works! :)
But I have question about rnnaec_demo, what audio format does it support for input? PCM? Thank you so much !


Best Regards!
Jason




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"shichaog"<notifications@github.com&gt;;
发送时间:&nbsp;2020年7月2日(星期四) 晚上8:56
收件人:&nbsp;"shichaog/RNNAec"<RNNAec@noreply.github.com&gt;;
抄送:&nbsp;"DaVinci"<77980695@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [shichaog/RNNAec] ISSUE about 'make' (#1)





  
Hi Shichao
 It seems to be something wrong when I make it, whether my configs is fault? Thank you Shichao!
 
jason@bogon:/rnnaec/RNNAec$ make make all-am make[1]: Entering directory '/home/jason/rnnaec/RNNAec' CC src/deecho.lo src/deecho.c: In function ‘compute_frame_features’: src/deecho.c:319:9: warning: unused variable ‘pitch_buf’ [-Wunused-variable] float pitch_buf[PITCH_BUF_SIZE]; ^~~~~~~~~ src/deecho.c: In function ‘gain_pitch_filter’: src/deecho.c:460:9: warning: unused variable ‘rf’ [-Wunused-variable] float rf[FREQ_SIZE] = {0}; ^
 src/deecho.c:459:9: warning: unused variable ‘r’ [-Wunused-variable]
 float r[NB_BANDS];
 ^
 src/deecho.c:457:37: warning: unused parameter ‘Ex_near’ [-Wunused-parameter]
 void gain_pitch_filter(const float *Ex_near, const float *Ex_far, const float *Exp_near, const float *Exp_far, float *g) {
 ^~~~~~~
 src/deecho.c:457:59: warning: unused parameter ‘Ex_far’ [-Wunused-parameter]
 void gain_pitch_filter(const float *Ex_near, const float *Ex_far, const float *Exp_near, const float *Exp_far, float *g) {
 ^~~~~~
 CC src/rnn.lo
 CC src/rnn_data.lo
 CC src/rnn_reader.lo
 CC src/pitch.lo
 CC src/kiss_fft.lo
 CC src/celt_lpc.lo
 CCLD librnnaec.la
 ar: u' modifier ignored since D' is the default (see `U')
 CC examples/rnnaec_demo.o
 examples/rnnaec_demo.c: In function ‘main’:
 examples/rnnaec_demo.c:53:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
 fread(tmp, sizeof(short), FRAME_SIZE, f1);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 examples/rnnaec_demo.c:56:5: warning: ignoring return value of ‘fread’, declared with attribute warn_unused_result [-Wunused-result]
 fread(tmp, sizeof(short), FRAME_SIZE, f2);
 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 CCLD examples/rnnaec_demo
 make[1]: *** No rule to make target 'AUTHORS', needed by 'all-am'. Stop.
 make[1]: Leaving directory '/home/jason/rnnaec/RNNAec'
 Makefile:411: recipe for target 'all' failed
 make: *** [all] Error 2
  
Sorry I fogot AUTHORS file, I'll push it later, Please try it tomorrow.

**Comment by shichaog** [comment]
Solved
