### ISSUE TITLE
请问 training 用的语音是怎么样的？

### ISSUE THREAD

**Issue by matt-audio** [shichaog/RNNAec#3]
你好：
请问一下: 
<far speech> <near speech> <far noise> <near noise>
这个 far speech 跟 near speech 都是随便的speech？
这个 far noise 跟 near noise 都是随便的noise？

没有任何的关系吗 ？

**Comment by shichaog** [comment]
> 你好：
> 请问一下:
> 
> 这个 far speech 跟 near speech 都是随便的speech？
> 这个 far noise 跟 near noise 都是随便的noise？
> 
> 没有任何的关系吗 ？

我的训练数据集使用的是纯净语音模拟生成的，如果你用实际语音，子集数据可以看最新readme，大概是我的真实数据集的1/4, 也欢迎把你的测试数据发我

**Comment by shichaog** [comment]
> > 你好：
> > 请问一下:
> > 这个 far speech 跟 near speech 都是随便的speech？
> > 这个 far noise 跟 near noise 都是随便的noise？
> > 没有任何的关系吗 ？
> 
> 我的训练数据集使用的是纯净语音模拟生成的，如果你用实际语音，子集数据可以看最新readme，大概是我的真实数据集的1/4, 也欢迎把你的测试数据发我

详见readme里中文，已附上部分训练数据
