### ISSUE TITLE
这种修改到底能不能用？

### ISSUE THREAD

**Issue by dttlgotv** [shichaog/RNNAec#4]
我试了您的demo，效果几乎没有。你的这种修改到底有没有成功的经验？难道只是为了卖书！

**Comment by shichaog** [comment]
> 我试了您的demo，效果几乎没有。你的这种修改到底有没有成功的经验？难道只是为了卖书！

我的训练数据集使用的是纯净语音模拟生成的，如果你用实际语音，可能存在1.delay， 2.far端信号在near经过传播之后存在非线性失真，3.数据中含噪声比较多，而这训练没有得到；但是并不意味着真实场景中所有情况不行，我试过有行的；另外开放了附带的一个子集数据可以看最新readme，也欢迎把你的测试数据发我，这样可以提高更复杂case
