### ISSUE TITLE
make 失败

### ISSUE THREAD

**Issue by owen-9527** [shichaog/RNNAec#5]
你好，按照readme, configure后执行 make操作出错
-----------------------------------------
make  all-am
make[1]: Entering directory '/data/work/2021_work/RNNAec-master'
make[1]: *** No rule to make target 'README', needed by 'all-am'.  Stop.
make[1]: Leaving directory '/data/work/2021_work/RNNAec-master'
Makefile:411: recipe for target 'all' failed
make: *** [all] Error 2
-----------------------------------------
是缺少文件吗？

另外，以上的错误会影响example demo的运行结果吗？demo可执行，但是AEC效果有点差的。

**Comment by owen-9527** [comment]
> ## 你好，按照readme, configure后执行 make操作出错
> ## make all-am
> make[1]: Entering directory '/data/work/2021_work/RNNAec-master'
> make[1]: *** No rule to make target 'README', needed by 'all-am'. Stop.
> make[1]: Leaving directory '/data/work/2021_work/RNNAec-master'
> Makefile:411: recipe for target 'all' failed
> make: *** [all] Error 2
> 是缺少文件吗？
> 
> 另外，以上的错误会影响example demo的运行结果吗？demo可执行，但是AEC效果有点差的。

#cp README.md README 
  以上命令应该解决了make的问题。
--然后看了下demo运行的结果还是一样的，echo基本没消除啊。

**Comment by shichaog** [comment]
> > ## 你好，按照readme, configure后执行 make操作出错
> > ## make all-am
> > make[1]: Entering directory '/data/work/2021_work/RNNAec-master'
> > make[1]: *** No rule to make target 'README', needed by 'all-am'. Stop.
> > make[1]: Leaving directory '/data/work/2021_work/RNNAec-master'
> > Makefile:411: recipe for target 'all' failed
> > make: *** [all] Error 2
> > 是缺少文件吗？
> > 另外，以上的错误会影响example demo的运行结果吗？demo可执行，但是AEC效果有点差的。
> 
> #cp README.md README
> 以上命令应该解决了make的问题。
> --然后看了下demo运行的结果还是一样的，echo基本没消除啊。

我想你该认真读一下readme里中文说明
